//
// Generated by JavaToPas v1.5 20161020 - 055741
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR = interface;

  JRClass = interface(JObjectClass)
    ['{AC9C6D14-A631-4752-A3FD-BF546B44CC6A}']
    function init : JR; cdecl;                                                  // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/R$styleable')]
  JR = interface(JObject)
    ['{A024A15D-F528-4E0E-8826-3E401E76CCD7}']
  end;

  TJR = class(TJavaGenericImport<JRClass, JR>)
  end;

implementation

end.
