//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.GoogleConversionPing;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.GoogleConversionPing_ConversionType,
  android.net.Uri;

type
  JGoogleConversionPing = interface;

  JGoogleConversionPingClass = interface(JObjectClass)
    ['{3E4BE3EB-8B5F-4E39-B6D7-AA45B67EA117}']
    function init : JGoogleConversionPing; cdecl;                               // ()V A: $1
    function registerReferrer(applicationContext : JContext; clickUri : JUri) : boolean; deprecated; cdecl;// (Landroid/content/Context;Landroid/net/Uri;)Z A: $9
    procedure recordConversionPing(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) ; deprecated; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
    procedure recordConversionPing(applicationContext : JContext; conversionId : JString; &type : JGoogleConversionPing_ConversionType; &label : JString; value : JString; isRepeatable : boolean) ; deprecated; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
    procedure recordRemarketingPing(applicationContext : JContext; conversionId : JString; &label : JString; screenName : JString; customParameters : JMap) ; deprecated; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/GoogleConversionPing$ConversionType')]
  JGoogleConversionPing = interface(JObject)
    ['{EDBEDCE9-4662-436F-9E82-35135EDEFACE}']
  end;

  TJGoogleConversionPing = class(TJavaGenericImport<JGoogleConversionPingClass, JGoogleConversionPing>)
  end;

implementation

end.
