//
// Generated by JavaToPas v1.5 20161020 - 055741
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.AdWordsConversionReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.g_d,
  android.net.Uri;

type
  JAdWordsConversionReporter = interface;

  JAdWordsConversionReporterClass = interface(JObjectClass)
    ['{060EFAB6-C5E3-4E70-9EC1-6CA31A751CE0}']
    function init(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; currencyCode : JString; isRepeatable : boolean) : JAdWordsConversionReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    function init(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) : JAdWordsConversionReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    function registerReferrer(applicationContext : JContext; clickUri : JUri) : boolean; cdecl;// (Landroid/content/Context;Landroid/net/Uri;)Z A: $9
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; currencyCode : JString; isRepeatable : boolean) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/AdWordsConversionReporter')]
  JAdWordsConversionReporter = interface(JObject)
    ['{9ADFAE00-85B0-4F12-B516-AEE748F78925}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJAdWordsConversionReporter = class(TJavaGenericImport<JAdWordsConversionReporterClass, JAdWordsConversionReporter>)
  end;

implementation

end.
