//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.DoubleClickAudienceReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  JDoubleClickAudienceReporter = interface;

  JDoubleClickAudienceReporterClass = interface(JObjectClass)
    ['{2339AA47-C383-44D6-A6CE-031DFDA1ACA7}']
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportActivity(applicationContext : JContext; adUnitId : JString; customParameters : JMap) ; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/util/Map;)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/DoubleClickAudienceReporter')]
  JDoubleClickAudienceReporter = interface(JObject)
    ['{498B12C1-08B0-442F-8DE4-D171D59886C8}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJDoubleClickAudienceReporter = class(TJavaGenericImport<JDoubleClickAudienceReporterClass, JDoubleClickAudienceReporter>)
  end;

implementation

end.
