//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.GoogleConversionPing_ConversionType;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JGoogleConversionPing_ConversionType = interface;

  JGoogleConversionPing_ConversionTypeClass = interface(JObjectClass)
    ['{3DD142AA-3DBA-4263-80E4-41F2C0A09F1E}']
    function _GetDOUBLECLICK_CONVERSION : JGoogleConversionPing_ConversionType; cdecl;//  A: $4019
    function _GetGOOGLE_CONVERSION : JGoogleConversionPing_ConversionType; cdecl;//  A: $4019
    function valueOf(&name : JString) : JGoogleConversionPing_ConversionType; cdecl;// (Ljava/lang/String;)Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $9
    function values : TJavaArray<JGoogleConversionPing_ConversionType>; cdecl;  // ()[Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $9
    property DOUBLECLICK_CONVERSION : JGoogleConversionPing_ConversionType read _GetDOUBLECLICK_CONVERSION;// Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $4019
    property GOOGLE_CONVERSION : JGoogleConversionPing_ConversionType read _GetGOOGLE_CONVERSION;// Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $4019
  end;

  [JavaSignature('com/google/ads/conversiontracking/GoogleConversionPing_ConversionType')]
  JGoogleConversionPing_ConversionType = interface(JObject)
    ['{4060364A-8E11-48A9-87AA-8B402F1E0DD9}']
  end;

  TJGoogleConversionPing_ConversionType = class(TJavaGenericImport<JGoogleConversionPing_ConversionTypeClass, JGoogleConversionPing_ConversionType>)
  end;

implementation

end.
