//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.g_d;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jg_d = interface;

  Jg_dClass = interface(JObjectClass)
    ['{0FB00A28-BB80-454F-B72A-82602E754C18}']
    function _Geta : Jg_d; cdecl;                                               //  A: $4019
    function _Getb : Jg_d; cdecl;                                               //  A: $4019
    function _Getc : Jg_d; cdecl;                                               //  A: $4019
    function _Getd : Jg_d; cdecl;                                               //  A: $4019
    function a : TJavaArray<Jg_d>; cdecl;                                       // ()[Lcom/google/ads/conversiontracking/g$d; A: $9
    property a : Jg_d read _Geta;                                               // Lcom/google/ads/conversiontracking/g$d; A: $4019
    property b : Jg_d read _Getb;                                               // Lcom/google/ads/conversiontracking/g$d; A: $4019
    property c : Jg_d read _Getc;                                               // Lcom/google/ads/conversiontracking/g$d; A: $4019
    property d : Jg_d read _Getd;                                               // Lcom/google/ads/conversiontracking/g$d; A: $4019
  end;

  [JavaSignature('com/google/ads/conversiontracking/g_d')]
  Jg_d = interface(JObject)
    ['{25B51FB4-8BE4-4366-9E36-673AEFD884B8}']
  end;

  TJg_d = class(TJavaGenericImport<Jg_dClass, Jg_d>)
  end;

implementation

end.
