//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.AdWordsRemarketingReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  JAdWordsRemarketingReporter = interface;

  JAdWordsRemarketingReporterClass = interface(JObjectClass)
    ['{D8051654-2C94-46DE-B27C-B21CF4820D37}']
    function init(applicationContext : JContext; conversionId : JString) : JAdWordsRemarketingReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;)V A: $1
    function init(applicationContext : JContext; conversionId : JString; customParameters : JMap) : JAdWordsRemarketingReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/util/Map;)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;)V A: $9
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; customParameters : JMap) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/util/Map;)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/AdWordsRemarketingReporter')]
  JAdWordsRemarketingReporter = interface(JObject)
    ['{4493D6A3-6812-4AB0-AA25-36ED2078B901}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJAdWordsRemarketingReporter = class(TJavaGenericImport<JAdWordsRemarketingReporterClass, JAdWordsRemarketingReporter>)
  end;

implementation

end.
