//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.d;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.g_c;

type
  Jd = interface;

  JdClass = interface(JObjectClass)
    ['{781DACBE-C1B3-45A6-9F69-4E2FFF60FE68}']
    function _Geta : boolean; cdecl;                                            //  A: $11
    function _Getb : boolean; cdecl;                                            //  A: $11
    function _Getc : Integer; cdecl;                                            //  A: $11
    function _Getd : Int64; cdecl;                                              //  A: $11
    function _Gete : JString; cdecl;                                            //  A: $11
    function _Getf : JString; cdecl;                                            //  A: $11
    function _Getg : JString; cdecl;                                            //  A: $11
    function _Geth : Int64; cdecl;                                              //  A: $1
    function init(Int64param0 : Int64; JStringparam1 : JString; JStringparam2 : JString; booleanparam3 : boolean; booleanparam4 : boolean; JStringparam5 : JString; Int64param6 : Int64; Integerparam7 : Integer) : Jd; cdecl; overload;// (JLjava/lang/String;Ljava/lang/String;ZZLjava/lang/String;JI)V A: $1
    function init(JStringparam0 : JString; Jg_cparam1 : Jg_c; booleanparam2 : boolean; booleanparam3 : boolean) : Jd; cdecl; overload;// (Ljava/lang/String;Lcom/google/ads/conversiontracking/g$c;ZZ)V A: $1
    procedure _Seth(Value : Int64) ; cdecl;                                     //  A: $1
    property a : boolean read _Geta;                                            // Z A: $11
    property b : boolean read _Getb;                                            // Z A: $11
    property c : Integer read _Getc;                                            // I A: $11
    property d : Int64 read _Getd;                                              // J A: $11
    property e : JString read _Gete;                                            // Ljava/lang/String; A: $11
    property f : JString read _Getf;                                            // Ljava/lang/String; A: $11
    property g : JString read _Getg;                                            // Ljava/lang/String; A: $11
    property h : Int64 read _Geth write _Seth;                                  // J A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/d')]
  Jd = interface(JObject)
    ['{EA676695-684E-4E9E-BADB-4D881FCE1A74}']
    function _Geth : Int64; cdecl;                                              //  A: $1
    procedure _Seth(Value : Int64) ; cdecl;                                     //  A: $1
    property h : Int64 read _Geth write _Seth;                                  // J A: $1
  end;

  TJd = class(TJavaGenericImport<JdClass, Jd>)
  end;

implementation

end.
