//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.GoogleConversionReporter_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.GoogleConversionReporter,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.g_c;

type
  JGoogleConversionReporter_1 = interface;

  JGoogleConversionReporter_1Class = interface(JObjectClass)
    ['{5946245F-B05B-417D-A227-E23FE2485CCB}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/GoogleConversionReporter_1')]
  JGoogleConversionReporter_1 = interface(JObject)
    ['{21E800D8-FF8B-4B82-B5EB-6C6DE8CF675C}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJGoogleConversionReporter_1 = class(TJavaGenericImport<JGoogleConversionReporter_1Class, JGoogleConversionReporter_1>)
  end;

implementation

end.
