//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.f;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.d,
  android.database.sqlite.SQLiteDatabase,
  android.database.Cursor;

type
  Jf_a = interface; // merged
  Jf = interface;

  JfClass = interface(JObjectClass)
    ['{C651BD60-4AEF-47FB-894B-CCDF6F93BE44}']
    function a : JSQLiteDatabase; cdecl; overload;                              // ()Landroid/database/sqlite/SQLiteDatabase; A: $1
    function a(Int64param0 : Int64) : JList; cdecl; overload;                   // (J)Ljava/util/List; A: $1
    function a(JCursorparam0 : JCursor) : Jd; cdecl; overload;                  // (Landroid/database/Cursor;)Lcom/google/ads/conversiontracking/d; A: $1
    function c : Integer; cdecl; overload;                                      // ()I A: $1
    function init(JContextparam0 : JContext) : Jf; cdecl;                       // (Landroid/content/Context;)V A: $1
    procedure a(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure b ; cdecl; overload;                                              // ()V A: $1
    procedure b(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure c(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure d ; cdecl;                                                        // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/f$a')]
  Jf = interface(JObject)
    ['{39E09C33-28B2-4A81-878E-F26DDD94C347}']
    function a : JSQLiteDatabase; cdecl; overload;                              // ()Landroid/database/sqlite/SQLiteDatabase; A: $1
    function a(Int64param0 : Int64) : JList; cdecl; overload;                   // (J)Ljava/util/List; A: $1
    function a(JCursorparam0 : JCursor) : Jd; cdecl; overload;                  // (Landroid/database/Cursor;)Lcom/google/ads/conversiontracking/d; A: $1
    function c : Integer; cdecl; overload;                                      // ()I A: $1
    procedure a(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure b ; cdecl; overload;                                              // ()V A: $1
    procedure b(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure c(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure d ; cdecl;                                                        // ()V A: $1
  end;

  TJf = class(TJavaGenericImport<JfClass, Jf>)
  end;

  // Merged from: .\com.google.ads.conversiontracking.f_a.pas
  Jf_aClass = interface(JObjectClass)
    ['{B6FAE931-26B1-4FA0-B03A-C8559C79F8A0}']
    function init(Jfparam0 : Jf; JContextparam1 : JContext; JStringparam2 : JString) : Jf_a; cdecl;// (Lcom/google/ads/conversiontracking/f;Landroid/content/Context;Ljava/lang/String;)V A: $1
    procedure onCreate(db : JSQLiteDatabase) ; cdecl;                           // (Landroid/database/sqlite/SQLiteDatabase;)V A: $1
    procedure onUpgrade(db : JSQLiteDatabase; oldVersion : Integer; newVersion : Integer) ; cdecl;// (Landroid/database/sqlite/SQLiteDatabase;II)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/f_a')]
  Jf_a = interface(JObject)
    ['{53D784DE-C14F-4470-95C9-1D123FDA9631}']
    procedure onCreate(db : JSQLiteDatabase) ; cdecl;                           // (Landroid/database/sqlite/SQLiteDatabase;)V A: $1
    procedure onUpgrade(db : JSQLiteDatabase; oldVersion : Integer; newVersion : Integer) ; cdecl;// (Landroid/database/sqlite/SQLiteDatabase;II)V A: $1
  end;

  TJf_a = class(TJavaGenericImport<Jf_aClass, Jf_a>)
  end;


implementation

end.
