//
// Generated by JavaToPas v1.5 20161020 - 055743
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.i;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.n,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.i_a;

type
  Ji = interface;

  JiClass = interface(JObjectClass)
    ['{F03F0434-CEC1-4A36-A08D-2AF76928DC73}']
    function a(JContextparam0 : JContext) : Ji_a; cdecl; overload;              // (Landroid/content/Context;)Lcom/google/ads/conversiontracking/i$a; A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/i$a')]
  Ji = interface(JObject)
    ['{96799AE6-7283-465E-AC5D-B8242E4777AF}']
  end;

  TJi = class(TJavaGenericImport<JiClass, Ji>)
  end;

implementation

end.
