//
// Generated by JavaToPas v1.5 20161020 - 055743
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.h_a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jh_a = interface;

  Jh_aClass = interface(JObjectClass)
    ['{3526DBB2-6F14-4925-A2CC-7A814EE7A108}']
    function _Geta : Integer; cdecl;                                            //  A: $19
    property a : Integer read _Geta;                                            // I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/h_a')]
  Jh_a = interface(JObject)
    ['{0400E2C5-6B92-4802-8641-B4C2E0A9CA6E}']
  end;

  TJh_a = class(TJavaGenericImport<Jh_aClass, Jh_a>)
  end;

const
  TJh_aa = 2130968589;

implementation

end.
