//
// Generated by JavaToPas v1.5 20161020 - 055741
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_drawable;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_drawable = interface;

  JR_drawableClass = interface(JObjectClass)
    ['{3BC7663F-B176-4F4A-8A44-3DCD3ADE38E4}']
    function _Getcommon_signin_btn_icon_dark : Integer; cdecl;                  //  A: $19
    function _Getcommon_signin_btn_icon_disabled_dark : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_icon_disabled_focus_dark : Integer; cdecl;   //  A: $19
    function _Getcommon_signin_btn_icon_disabled_focus_light : Integer; cdecl;  //  A: $19
    function _Getcommon_signin_btn_icon_disabled_light : Integer; cdecl;        //  A: $19
    function _Getcommon_signin_btn_icon_focus_dark : Integer; cdecl;            //  A: $19
    function _Getcommon_signin_btn_icon_focus_light : Integer; cdecl;           //  A: $19
    function _Getcommon_signin_btn_icon_light : Integer; cdecl;                 //  A: $19
    function _Getcommon_signin_btn_icon_normal_dark : Integer; cdecl;           //  A: $19
    function _Getcommon_signin_btn_icon_normal_light : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_icon_pressed_dark : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_icon_pressed_light : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_text_dark : Integer; cdecl;                  //  A: $19
    function _Getcommon_signin_btn_text_disabled_dark : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_text_disabled_focus_dark : Integer; cdecl;   //  A: $19
    function _Getcommon_signin_btn_text_disabled_focus_light : Integer; cdecl;  //  A: $19
    function _Getcommon_signin_btn_text_disabled_light : Integer; cdecl;        //  A: $19
    function _Getcommon_signin_btn_text_focus_dark : Integer; cdecl;            //  A: $19
    function _Getcommon_signin_btn_text_focus_light : Integer; cdecl;           //  A: $19
    function _Getcommon_signin_btn_text_light : Integer; cdecl;                 //  A: $19
    function _Getcommon_signin_btn_text_normal_dark : Integer; cdecl;           //  A: $19
    function _Getcommon_signin_btn_text_normal_light : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_text_pressed_dark : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_text_pressed_light : Integer; cdecl;         //  A: $19
    function _Getic_plusone_medium_off_client : Integer; cdecl;                 //  A: $19
    function _Getic_plusone_small_off_client : Integer; cdecl;                  //  A: $19
    function _Getic_plusone_standard_off_client : Integer; cdecl;               //  A: $19
    function _Getic_plusone_tall_off_client : Integer; cdecl;                   //  A: $19
    function init : JR_drawable; cdecl;                                         // ()V A: $1
    property common_signin_btn_icon_dark : Integer read _Getcommon_signin_btn_icon_dark;// I A: $19
    property common_signin_btn_icon_disabled_dark : Integer read _Getcommon_signin_btn_icon_disabled_dark;// I A: $19
    property common_signin_btn_icon_disabled_focus_dark : Integer read _Getcommon_signin_btn_icon_disabled_focus_dark;// I A: $19
    property common_signin_btn_icon_disabled_focus_light : Integer read _Getcommon_signin_btn_icon_disabled_focus_light;// I A: $19
    property common_signin_btn_icon_disabled_light : Integer read _Getcommon_signin_btn_icon_disabled_light;// I A: $19
    property common_signin_btn_icon_focus_dark : Integer read _Getcommon_signin_btn_icon_focus_dark;// I A: $19
    property common_signin_btn_icon_focus_light : Integer read _Getcommon_signin_btn_icon_focus_light;// I A: $19
    property common_signin_btn_icon_light : Integer read _Getcommon_signin_btn_icon_light;// I A: $19
    property common_signin_btn_icon_normal_dark : Integer read _Getcommon_signin_btn_icon_normal_dark;// I A: $19
    property common_signin_btn_icon_normal_light : Integer read _Getcommon_signin_btn_icon_normal_light;// I A: $19
    property common_signin_btn_icon_pressed_dark : Integer read _Getcommon_signin_btn_icon_pressed_dark;// I A: $19
    property common_signin_btn_icon_pressed_light : Integer read _Getcommon_signin_btn_icon_pressed_light;// I A: $19
    property common_signin_btn_text_dark : Integer read _Getcommon_signin_btn_text_dark;// I A: $19
    property common_signin_btn_text_disabled_dark : Integer read _Getcommon_signin_btn_text_disabled_dark;// I A: $19
    property common_signin_btn_text_disabled_focus_dark : Integer read _Getcommon_signin_btn_text_disabled_focus_dark;// I A: $19
    property common_signin_btn_text_disabled_focus_light : Integer read _Getcommon_signin_btn_text_disabled_focus_light;// I A: $19
    property common_signin_btn_text_disabled_light : Integer read _Getcommon_signin_btn_text_disabled_light;// I A: $19
    property common_signin_btn_text_focus_dark : Integer read _Getcommon_signin_btn_text_focus_dark;// I A: $19
    property common_signin_btn_text_focus_light : Integer read _Getcommon_signin_btn_text_focus_light;// I A: $19
    property common_signin_btn_text_light : Integer read _Getcommon_signin_btn_text_light;// I A: $19
    property common_signin_btn_text_normal_dark : Integer read _Getcommon_signin_btn_text_normal_dark;// I A: $19
    property common_signin_btn_text_normal_light : Integer read _Getcommon_signin_btn_text_normal_light;// I A: $19
    property common_signin_btn_text_pressed_dark : Integer read _Getcommon_signin_btn_text_pressed_dark;// I A: $19
    property common_signin_btn_text_pressed_light : Integer read _Getcommon_signin_btn_text_pressed_light;// I A: $19
    property ic_plusone_medium_off_client : Integer read _Getic_plusone_medium_off_client;// I A: $19
    property ic_plusone_small_off_client : Integer read _Getic_plusone_small_off_client;// I A: $19
    property ic_plusone_standard_off_client : Integer read _Getic_plusone_standard_off_client;// I A: $19
    property ic_plusone_tall_off_client : Integer read _Getic_plusone_tall_off_client;// I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_drawable')]
  JR_drawable = interface(JObject)
    ['{81C87567-5EEA-46D3-8409-5F1F566A6333}']
  end;

  TJR_drawable = class(TJavaGenericImport<JR_drawableClass, JR_drawable>)
  end;

const
  TJR_drawablecommon_signin_btn_icon_dark = 2130837504;
  TJR_drawablecommon_signin_btn_icon_disabled_dark = 2130837505;
  TJR_drawablecommon_signin_btn_icon_disabled_focus_dark = 2130837506;
  TJR_drawablecommon_signin_btn_icon_disabled_focus_light = 2130837507;
  TJR_drawablecommon_signin_btn_icon_disabled_light = 2130837508;
  TJR_drawablecommon_signin_btn_icon_focus_dark = 2130837509;
  TJR_drawablecommon_signin_btn_icon_focus_light = 2130837510;
  TJR_drawablecommon_signin_btn_icon_light = 2130837511;
  TJR_drawablecommon_signin_btn_icon_normal_dark = 2130837512;
  TJR_drawablecommon_signin_btn_icon_normal_light = 2130837513;
  TJR_drawablecommon_signin_btn_icon_pressed_dark = 2130837514;
  TJR_drawablecommon_signin_btn_icon_pressed_light = 2130837515;
  TJR_drawablecommon_signin_btn_text_dark = 2130837516;
  TJR_drawablecommon_signin_btn_text_disabled_dark = 2130837517;
  TJR_drawablecommon_signin_btn_text_disabled_focus_dark = 2130837518;
  TJR_drawablecommon_signin_btn_text_disabled_focus_light = 2130837519;
  TJR_drawablecommon_signin_btn_text_disabled_light = 2130837520;
  TJR_drawablecommon_signin_btn_text_focus_dark = 2130837521;
  TJR_drawablecommon_signin_btn_text_focus_light = 2130837522;
  TJR_drawablecommon_signin_btn_text_light = 2130837523;
  TJR_drawablecommon_signin_btn_text_normal_dark = 2130837524;
  TJR_drawablecommon_signin_btn_text_normal_light = 2130837525;
  TJR_drawablecommon_signin_btn_text_pressed_dark = 2130837526;
  TJR_drawablecommon_signin_btn_text_pressed_light = 2130837527;
  TJR_drawableic_plusone_medium_off_client = 2130837528;
  TJR_drawableic_plusone_small_off_client = 2130837529;
  TJR_drawableic_plusone_standard_off_client = 2130837530;
  TJR_drawableic_plusone_tall_off_client = 2130837531;

implementation

end.
