//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.g_2;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jg_2 = interface;

  Jg_2Class = interface(JObjectClass)
    ['{2D217BBC-367A-4599-B527-5D4AFBD71938}']
  end;

  [JavaSignature('com/google/ads/conversiontracking/g_2')]
  Jg_2 = interface(JObject)
    ['{0E684156-828B-4E09-9D91-8B9BF515713E}']
  end;

  TJg_2 = class(TJavaGenericImport<Jg_2Class, Jg_2>)
  end;

implementation

end.
