//
// Generated by JavaToPas v1.5 20161020 - 055741
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_color;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_color = interface;

  JR_colorClass = interface(JObjectClass)
    ['{A2619DB8-D350-4104-8D8B-57E0E796DB61}']
    function _Getcommon_action_bar_splitter : Integer; cdecl;                   //  A: $19
    function _Getcommon_signin_btn_dark_text_default : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_dark_text_disabled : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_dark_text_focused : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_dark_text_pressed : Integer; cdecl;          //  A: $19
    function _Getcommon_signin_btn_default_background : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_light_text_default : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_light_text_disabled : Integer; cdecl;        //  A: $19
    function _Getcommon_signin_btn_light_text_focused : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_light_text_pressed : Integer; cdecl;         //  A: $19
    function _Getcommon_signin_btn_text_dark : Integer; cdecl;                  //  A: $19
    function _Getcommon_signin_btn_text_light : Integer; cdecl;                 //  A: $19
    function init : JR_color; cdecl;                                            // ()V A: $1
    property common_action_bar_splitter : Integer read _Getcommon_action_bar_splitter;// I A: $19
    property common_signin_btn_dark_text_default : Integer read _Getcommon_signin_btn_dark_text_default;// I A: $19
    property common_signin_btn_dark_text_disabled : Integer read _Getcommon_signin_btn_dark_text_disabled;// I A: $19
    property common_signin_btn_dark_text_focused : Integer read _Getcommon_signin_btn_dark_text_focused;// I A: $19
    property common_signin_btn_dark_text_pressed : Integer read _Getcommon_signin_btn_dark_text_pressed;// I A: $19
    property common_signin_btn_default_background : Integer read _Getcommon_signin_btn_default_background;// I A: $19
    property common_signin_btn_light_text_default : Integer read _Getcommon_signin_btn_light_text_default;// I A: $19
    property common_signin_btn_light_text_disabled : Integer read _Getcommon_signin_btn_light_text_disabled;// I A: $19
    property common_signin_btn_light_text_focused : Integer read _Getcommon_signin_btn_light_text_focused;// I A: $19
    property common_signin_btn_light_text_pressed : Integer read _Getcommon_signin_btn_light_text_pressed;// I A: $19
    property common_signin_btn_text_dark : Integer read _Getcommon_signin_btn_text_dark;// I A: $19
    property common_signin_btn_text_light : Integer read _Getcommon_signin_btn_text_light;// I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_color')]
  JR_color = interface(JObject)
    ['{27DBAF67-B4B2-4F84-911E-7BBA254CC4B0}']
  end;

  TJR_color = class(TJavaGenericImport<JR_colorClass, JR_color>)
  end;

const
  TJR_colorcommon_action_bar_splitter = 2130903049;
  TJR_colorcommon_signin_btn_dark_text_default = 2130903040;
  TJR_colorcommon_signin_btn_dark_text_disabled = 2130903042;
  TJR_colorcommon_signin_btn_dark_text_focused = 2130903043;
  TJR_colorcommon_signin_btn_dark_text_pressed = 2130903041;
  TJR_colorcommon_signin_btn_default_background = 2130903048;
  TJR_colorcommon_signin_btn_light_text_default = 2130903044;
  TJR_colorcommon_signin_btn_light_text_disabled = 2130903046;
  TJR_colorcommon_signin_btn_light_text_focused = 2130903047;
  TJR_colorcommon_signin_btn_light_text_pressed = 2130903045;
  TJR_colorcommon_signin_btn_text_dark = 2130903050;
  TJR_colorcommon_signin_btn_text_light = 2130903051;

implementation

end.
