//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.g_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.content.SharedPreferences,
  com.google.ads.conversiontracking.g_b;

type
  Jg_1 = interface;

  Jg_1Class = interface(JObjectClass)
    ['{7A0E3626-7E4D-40E3-9CAE-EDCE15A0235F}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/g_1')]
  Jg_1 = interface(JObject)
    ['{7FA66D40-A41A-4801-8C0D-563BFFDB4980}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJg_1 = class(TJavaGenericImport<Jg_1Class, Jg_1>)
  end;

implementation

end.
