//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.DoubleClickConversionReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  JDoubleClickConversionReporter = interface;

  JDoubleClickConversionReporterClass = interface(JObjectClass)
    ['{9DAC53D1-385E-4216-BAA5-B0A04E9E3CF4}']
    function init(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) : JDoubleClickConversionReporter; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) ; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/DoubleClickConversionReporter')]
  JDoubleClickConversionReporter = interface(JObject)
    ['{4EE4A87E-9525-495A-89A2-08DF7F428123}']
  end;

  TJDoubleClickConversionReporter = class(TJavaGenericImport<JDoubleClickConversionReporterClass, JDoubleClickConversionReporter>)
  end;

implementation

end.
