//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.c;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.b,
  Androidapi.JNI.GraphicsContentViewText,
  Androidapi.JNI.os,
  android.content.SharedPreferences;

type
  Jc = interface;

  JcClass = interface(JObjectClass)
    ['{3BD218BC-DF57-4C72-93C4-978F2C02F1F6}']
    function a(JContextparam0 : JContext) : Jc; cdecl; overload;                // (Landroid/content/Context;)Lcom/google/ads/conversiontracking/c; A: $9
    function d(JStringparam0 : JString) : boolean; cdecl; overload;             // (Ljava/lang/String;)Z A: $1
    procedure a(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure b(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure c(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/c')]
  Jc = interface(JObject)
    ['{062A708F-CA29-48D3-A9E0-A17CF7A98945}']
    function d(JStringparam0 : JString) : boolean; cdecl; overload;             // (Ljava/lang/String;)Z A: $1
    procedure a(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure b(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure c(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJc = class(TJavaGenericImport<JcClass, Jc>)
  end;

implementation

end.
