//
// Generated by JavaToPas v1.5 20161020 - 055741
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_integer;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_integer = interface;

  JR_integerClass = interface(JObjectClass)
    ['{06E0A47E-26E1-4FF5-9CA6-A5AA5E992C81}']
    function _Getgoogle_play_services_version : Integer; cdecl;                 //  A: $19
    function init : JR_integer; cdecl;                                          // ()V A: $1
    property google_play_services_version : Integer read _Getgoogle_play_services_version;// I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_integer')]
  JR_integer = interface(JObject)
    ['{AAF10B42-F1CC-48CA-BA3E-EF217F07C5DD}']
  end;

  TJR_integer = class(TJavaGenericImport<JR_integerClass, JR_integer>)
  end;

const
  TJR_integergoogle_play_services_version = 2131034112;

implementation

end.
