//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.b;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  Jb = interface;

  JbClass = interface(JObjectClass)
    ['{538263F1-C157-437A-9C51-9A0C4D4B4AD8}']
    function init(JContextparam0 : JContext) : Jb; cdecl;                       // (Landroid/content/Context;)V A: $1
    procedure a(JStringparam0 : JString; Int64param1 : Int64) ; cdecl;          // (Ljava/lang/String;J)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/b')]
  Jb = interface(JObject)
    ['{C4A24844-E561-493C-9298-678457DBD84F}']
    procedure a(JStringparam0 : JString; Int64param1 : Int64) ; cdecl;          // (Ljava/lang/String;J)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJb = class(TJavaGenericImport<JbClass, Jb>)
  end;

implementation

end.
