//
// Generated by JavaToPas v1.5 20161020 - 055743
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.k;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.content.Intent;

type
  Jk = interface;

  JkClass = interface(JObjectClass)
    ['{8E9F2578-1038-4831-9857-A5E65C1EF28F}']
  end;

  [JavaSignature('com/google/ads/conversiontracking/k')]
  Jk = interface(JObject)
    ['{8D8461A9-A607-4A47-899E-F1AC890A016A}']
  end;

  TJk = class(TJavaGenericImport<JkClass, Jk>)
  end;

implementation

end.
