//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.GoogleConversionReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.g_c;

type
  JGoogleConversionReporter = interface;

  JGoogleConversionReporterClass = interface(JObjectClass)
    ['{15A7A5B6-D54D-4FBA-AC97-83F834952310}']
    function init : JGoogleConversionReporter; cdecl;                           // ()V A: $1
    procedure report ; cdecl;                                                   // ()V A: $401
  end;

  [JavaSignature('com/google/ads/conversiontracking/GoogleConversionReporter')]
  JGoogleConversionReporter = interface(JObject)
    ['{6F22BF17-F18C-4CC2-BED8-C699B0E516DC}']
    procedure report ; cdecl;                                                   // ()V A: $401
  end;

  TJGoogleConversionReporter = class(TJavaGenericImport<JGoogleConversionReporterClass, JGoogleConversionReporter>)
  end;

implementation

end.
