//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.a_a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.a_b,
  com.google.ads.conversiontracking.a_c,
  Androidapi.JNI.GraphicsContentViewText;

type
  Ja_a = interface;

  Ja_aClass = interface(JObjectClass)
    ['{A7CAD931-43E7-47B7-9338-10F668D6634B}']
    function getPackageManager : JPackageManager; cdecl;                        // ()Landroid/content/pm/PackageManager; A: $1
    function getResources : JResources; cdecl;                                  // ()Landroid/content/res/Resources; A: $1
    function init(JContextparam0 : JContext) : Ja_a; cdecl;                     // (Landroid/content/Context;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/a_a')]
  Ja_a = interface(JObject)
    ['{835DB5B8-8FC6-4BD1-984A-35C861554170}']
    function getPackageManager : JPackageManager; cdecl;                        // ()Landroid/content/pm/PackageManager; A: $1
    function getResources : JResources; cdecl;                                  // ()Landroid/content/res/Resources; A: $1
  end;

  TJa_a = class(TJavaGenericImport<Ja_aClass, Ja_a>)
  end;

implementation

end.
