//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.a_c;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  Ja_c = interface;

  Ja_cClass = interface(JObjectClass)
    ['{E36A4109-3269-49AC-9E9B-A7E8D2BF2122}']
    function getString(id : Integer) : JString; cdecl;                          // (I)Ljava/lang/String; A: $1
    function init(JResourcesparam0 : JResources) : Ja_c; cdecl;                 // (Landroid/content/res/Resources;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/a_c')]
  Ja_c = interface(JObject)
    ['{2A0C4F3A-980D-44A7-BFC8-896CD253A563}']
    function getString(id : Integer) : JString; cdecl;                          // (I)Ljava/lang/String; A: $1
  end;

  TJa_c = class(TJavaGenericImport<Ja_cClass, Ja_c>)
  end;

implementation

end.
