//
// Generated by JavaToPas v1.5 20161020 - 055743
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.s;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Js = interface;

  JsClass = interface(JObjectClass)
    ['{498EB960-68E7-404A-B665-BA874FC6B344}']
    function a(TJavaArrayByteparam0 : TJavaArray<Byte>; Integerparam1 : Integer; Integerparam2 : Integer; TJavaArrayCharparam3 : TJavaArray<Char>; booleanparam4 : boolean) : JString; cdecl; overload;// ([BII[CZ)Ljava/lang/String; A: $9
    function a(TJavaArrayByteparam0 : TJavaArray<Byte>; booleanparam1 : boolean) : JString; deprecated; cdecl; overload;// ([BZ)Ljava/lang/String; A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/s')]
  Js = interface(JObject)
    ['{C02D9926-4318-463C-AF0D-8A9CEE15001B}']
  end;

  TJs = class(TJavaGenericImport<JsClass, Js>)
  end;

implementation

end.
