//
// Generated by JavaToPas v1.5 20161020 - 055742
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.InstallReceiver;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  android.content.Intent;

type
  JInstallReceiver = interface;

  JInstallReceiverClass = interface(JObjectClass)
    ['{26E86C73-15F3-4093-B543-870BC00306F8}']
    function init : JInstallReceiver; cdecl;                                    // ()V A: $1
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/InstallReceiver')]
  JInstallReceiver = interface(JObject)
    ['{3D1F009B-1AB9-438D-A13F-177DF18702AD}']
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  TJInstallReceiver = class(TJavaGenericImport<JInstallReceiverClass, JInstallReceiver>)
  end;

implementation

end.
