//
// Generated by JavaToPas v1.5 20161020 - 055741
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_attr;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_attr = interface;

  JR_attrClass = interface(JObjectClass)
    ['{CC03F707-FDB0-4195-8F3E-E403FB631EFA}']
    function _GetadSize : Integer; cdecl;                                       //  A: $19
    function _GetadSizes : Integer; cdecl;                                      //  A: $19
    function _GetadUnitId : Integer; cdecl;                                     //  A: $19
    function _GetallowShortcuts : Integer; cdecl;                               //  A: $19
    function _GetcameraBearing : Integer; cdecl;                                //  A: $19
    function _GetcameraTargetLat : Integer; cdecl;                              //  A: $19
    function _GetcameraTargetLng : Integer; cdecl;                              //  A: $19
    function _GetcameraTilt : Integer; cdecl;                                   //  A: $19
    function _GetcameraZoom : Integer; cdecl;                                   //  A: $19
    function _GetcontentProviderUri : Integer; cdecl;                           //  A: $19
    function _GetcorpusId : Integer; cdecl;                                     //  A: $19
    function _GetcorpusVersion : Integer; cdecl;                                //  A: $19
    function _GetdefaultIntentAction : Integer; cdecl;                          //  A: $19
    function _GetdefaultIntentActivity : Integer; cdecl;                        //  A: $19
    function _GetdefaultIntentData : Integer; cdecl;                            //  A: $19
    function _GetfeatureType : Integer; cdecl;                                  //  A: $19
    function _GetindexPrefixes : Integer; cdecl;                                //  A: $19
    function _GetmapType : Integer; cdecl;                                      //  A: $19
    function _GetnoIndex : Integer; cdecl;                                      //  A: $19
    function _GetparamName : Integer; cdecl;                                    //  A: $19
    function _GetparamValue : Integer; cdecl;                                   //  A: $19
    function _GetsearchEnabled : Integer; cdecl;                                //  A: $19
    function _GetsearchLabel : Integer; cdecl;                                  //  A: $19
    function _GetsectionContent : Integer; cdecl;                               //  A: $19
    function _GetsectionFormat : Integer; cdecl;                                //  A: $19
    function _GetsectionId : Integer; cdecl;                                    //  A: $19
    function _GetsectionType : Integer; cdecl;                                  //  A: $19
    function _GetsectionWeight : Integer; cdecl;                                //  A: $19
    function _GetsettingsDescription : Integer; cdecl;                          //  A: $19
    function _GetsubsectionSeparator : Integer; cdecl;                          //  A: $19
    function _Gettrimmable : Integer; cdecl;                                    //  A: $19
    function _GetuiCompass : Integer; cdecl;                                    //  A: $19
    function _GetuiRotateGestures : Integer; cdecl;                             //  A: $19
    function _GetuiScrollGestures : Integer; cdecl;                             //  A: $19
    function _GetuiTiltGestures : Integer; cdecl;                               //  A: $19
    function _GetuiZoomControls : Integer; cdecl;                               //  A: $19
    function _GetuiZoomGestures : Integer; cdecl;                               //  A: $19
    function _GetuseViewLifecycle : Integer; cdecl;                             //  A: $19
    function _GetzOrderOnTop : Integer; cdecl;                                  //  A: $19
    function init : JR_attr; cdecl;                                             // ()V A: $1
    property adSize : Integer read _GetadSize;                                  // I A: $19
    property adSizes : Integer read _GetadSizes;                                // I A: $19
    property adUnitId : Integer read _GetadUnitId;                              // I A: $19
    property allowShortcuts : Integer read _GetallowShortcuts;                  // I A: $19
    property cameraBearing : Integer read _GetcameraBearing;                    // I A: $19
    property cameraTargetLat : Integer read _GetcameraTargetLat;                // I A: $19
    property cameraTargetLng : Integer read _GetcameraTargetLng;                // I A: $19
    property cameraTilt : Integer read _GetcameraTilt;                          // I A: $19
    property cameraZoom : Integer read _GetcameraZoom;                          // I A: $19
    property contentProviderUri : Integer read _GetcontentProviderUri;          // I A: $19
    property corpusId : Integer read _GetcorpusId;                              // I A: $19
    property corpusVersion : Integer read _GetcorpusVersion;                    // I A: $19
    property defaultIntentAction : Integer read _GetdefaultIntentAction;        // I A: $19
    property defaultIntentActivity : Integer read _GetdefaultIntentActivity;    // I A: $19
    property defaultIntentData : Integer read _GetdefaultIntentData;            // I A: $19
    property featureType : Integer read _GetfeatureType;                        // I A: $19
    property indexPrefixes : Integer read _GetindexPrefixes;                    // I A: $19
    property mapType : Integer read _GetmapType;                                // I A: $19
    property noIndex : Integer read _GetnoIndex;                                // I A: $19
    property paramName : Integer read _GetparamName;                            // I A: $19
    property paramValue : Integer read _GetparamValue;                          // I A: $19
    property searchEnabled : Integer read _GetsearchEnabled;                    // I A: $19
    property searchLabel : Integer read _GetsearchLabel;                        // I A: $19
    property sectionContent : Integer read _GetsectionContent;                  // I A: $19
    property sectionFormat : Integer read _GetsectionFormat;                    // I A: $19
    property sectionId : Integer read _GetsectionId;                            // I A: $19
    property sectionType : Integer read _GetsectionType;                        // I A: $19
    property sectionWeight : Integer read _GetsectionWeight;                    // I A: $19
    property settingsDescription : Integer read _GetsettingsDescription;        // I A: $19
    property subsectionSeparator : Integer read _GetsubsectionSeparator;        // I A: $19
    property trimmable : Integer read _Gettrimmable;                            // I A: $19
    property uiCompass : Integer read _GetuiCompass;                            // I A: $19
    property uiRotateGestures : Integer read _GetuiRotateGestures;              // I A: $19
    property uiScrollGestures : Integer read _GetuiScrollGestures;              // I A: $19
    property uiTiltGestures : Integer read _GetuiTiltGestures;                  // I A: $19
    property uiZoomControls : Integer read _GetuiZoomControls;                  // I A: $19
    property uiZoomGestures : Integer read _GetuiZoomGestures;                  // I A: $19
    property useViewLifecycle : Integer read _GetuseViewLifecycle;              // I A: $19
    property zOrderOnTop : Integer read _GetzOrderOnTop;                        // I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_attr')]
  JR_attr = interface(JObject)
    ['{61F34463-A5AF-4D59-86B0-ADDBE274989A}']
  end;

  TJR_attr = class(TJavaGenericImport<JR_attrClass, JR_attr>)
  end;

const
  TJR_attradSize = 2130771968;
  TJR_attradSizes = 2130771969;
  TJR_attradUnitId = 2130771970;
  TJR_attrallowShortcuts = 2130771990;
  TJR_attrcameraBearing = 2130771994;
  TJR_attrcameraTargetLat = 2130771995;
  TJR_attrcameraTargetLng = 2130771996;
  TJR_attrcameraTilt = 2130771997;
  TJR_attrcameraZoom = 2130771998;
  TJR_attrcontentProviderUri = 2130771973;
  TJR_attrcorpusId = 2130771971;
  TJR_attrcorpusVersion = 2130771972;
  TJR_attrdefaultIntentAction = 2130771987;
  TJR_attrdefaultIntentActivity = 2130771989;
  TJR_attrdefaultIntentData = 2130771988;
  TJR_attrfeatureType = 2130771981;
  TJR_attrindexPrefixes = 2130771979;
  TJR_attrmapType = 2130771993;
  TJR_attrnoIndex = 2130771977;
  TJR_attrparamName = 2130771982;
  TJR_attrparamValue = 2130771983;
  TJR_attrsearchEnabled = 2130771984;
  TJR_attrsearchLabel = 2130771985;
  TJR_attrsectionContent = 2130771992;
  TJR_attrsectionFormat = 2130771976;
  TJR_attrsectionId = 2130771975;
  TJR_attrsectionType = 2130771991;
  TJR_attrsectionWeight = 2130771978;
  TJR_attrsettingsDescription = 2130771986;
  TJR_attrsubsectionSeparator = 2130771980;
  TJR_attrtrimmable = 2130771974;
  TJR_attruiCompass = 2130771999;
  TJR_attruiRotateGestures = 2130772000;
  TJR_attruiScrollGestures = 2130772001;
  TJR_attruiTiltGestures = 2130772002;
  TJR_attruiZoomControls = 2130772003;
  TJR_attruiZoomGestures = 2130772004;
  TJR_attruseViewLifecycle = 2130772005;
  TJR_attrzOrderOnTop = 2130772006;

implementation

end.
