//
// Generated by JavaToPas v1.5 20161020 - 055743
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.h;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jh = interface;

  JhClass = interface(JObjectClass)
    ['{C88B9140-7603-4A49-9903-AD3A4421E41B}']
  end;

  [JavaSignature('com/google/ads/conversiontracking/h$a')]
  Jh = interface(JObject)
    ['{6E114496-2C13-45D3-AC89-A11085E5E52B}']
  end;

  TJh = class(TJavaGenericImport<JhClass, Jh>)
  end;

implementation

end.
