//
// Generated by JavaToPas v1.5 20161020 - 055743
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.q;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jq = interface;

  JqClass = interface(JObjectClass)
    ['{0C0F2A53-9B62-45D7-8A74-8FF6AAA18D28}']
    function a : JString; cdecl; overload;                                      // ()Ljava/lang/String; A: $401
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function a(booleanparam0 : boolean) : boolean; cdecl; overload;             // (Z)Z A: $401
    procedure a(JStringparam0 : JString; booleanparam1 : boolean) ; cdecl; overload;// (Ljava/lang/String;Z)V A: $401
  end;

  [JavaSignature('com/google/ads/conversiontracking/q$a')]
  Jq = interface(JObject)
    ['{21147576-9FC0-4EC2-B061-F0F95AE967AC}']
    function a : JString; cdecl; overload;                                      // ()Ljava/lang/String; A: $401
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function a(booleanparam0 : boolean) : boolean; cdecl; overload;             // (Z)Z A: $401
    procedure a(JStringparam0 : JString; booleanparam1 : boolean) ; cdecl; overload;// (Ljava/lang/String;Z)V A: $401
  end;

  TJq = class(TJavaGenericImport<JqClass, Jq>)
  end;

implementation

end.
