//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_id;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_id = interface;

  JR_idClass = interface(JObjectClass)
    ['{A26DAA8A-7603-4F73-AE1F-395CFE45435A}']
    function _Getdemote_common_words : Integer; cdecl;                          //  A: $19
    function _Getdemote_rfc822_hostnames : Integer; cdecl;                      //  A: $19
    function _Gethtml : Integer; cdecl;                                         //  A: $19
    function _Gethybrid : Integer; cdecl;                                       //  A: $19
    function _Geticon_uri : Integer; cdecl;                                     //  A: $19
    function _Getintent_action : Integer; cdecl;                                //  A: $19
    function _Getintent_activity : Integer; cdecl;                              //  A: $19
    function _Getintent_data : Integer; cdecl;                                  //  A: $19
    function _Getintent_data_id : Integer; cdecl;                               //  A: $19
    function _Getintent_extra_data : Integer; cdecl;                            //  A: $19
    function _Getlarge_icon_uri : Integer; cdecl;                               //  A: $19
    function _Getmatch_global_nicknames : Integer; cdecl;                       //  A: $19
    function _Getnone : Integer; cdecl;                                         //  A: $19
    function _Getnormal : Integer; cdecl;                                       //  A: $19
    function _Getplain : Integer; cdecl;                                        //  A: $19
    function _Getrfc822 : Integer; cdecl;                                       //  A: $19
    function _Getsatellite : Integer; cdecl;                                    //  A: $19
    function _Getterrain : Integer; cdecl;                                      //  A: $19
    function _Gettext1 : Integer; cdecl;                                        //  A: $19
    function _Gettext2 : Integer; cdecl;                                        //  A: $19
    function init : JR_id; cdecl;                                               // ()V A: $1
    property demote_common_words : Integer read _Getdemote_common_words;        // I A: $19
    property demote_rfc822_hostnames : Integer read _Getdemote_rfc822_hostnames;// I A: $19
    property html : Integer read _Gethtml;                                      // I A: $19
    property hybrid : Integer read _Gethybrid;                                  // I A: $19
    property icon_uri : Integer read _Geticon_uri;                              // I A: $19
    property intent_action : Integer read _Getintent_action;                    // I A: $19
    property intent_activity : Integer read _Getintent_activity;                // I A: $19
    property intent_data : Integer read _Getintent_data;                        // I A: $19
    property intent_data_id : Integer read _Getintent_data_id;                  // I A: $19
    property intent_extra_data : Integer read _Getintent_extra_data;            // I A: $19
    property large_icon_uri : Integer read _Getlarge_icon_uri;                  // I A: $19
    property match_global_nicknames : Integer read _Getmatch_global_nicknames;  // I A: $19
    property none : Integer read _Getnone;                                      // I A: $19
    property normal : Integer read _Getnormal;                                  // I A: $19
    property plain : Integer read _Getplain;                                    // I A: $19
    property rfc822 : Integer read _Getrfc822;                                  // I A: $19
    property satellite : Integer read _Getsatellite;                            // I A: $19
    property terrain : Integer read _Getterrain;                                // I A: $19
    property text1 : Integer read _Gettext1;                                    // I A: $19
    property text2 : Integer read _Gettext2;                                    // I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_id')]
  JR_id = interface(JObject)
    ['{8952A53E-717F-4EAD-B47C-7A3D33A6E6D1}']
  end;

  TJR_id = class(TJavaGenericImport<JR_idClass, JR_id>)
  end;

const
  TJR_iddemote_common_words = 2131099651;
  TJR_iddemote_rfc822_hostnames = 2131099652;
  TJR_idhtml = 2131099648;
  TJR_idhybrid = 2131099663;
  TJR_idicon_uri = 2131099654;
  TJR_idintent_action = 2131099655;
  TJR_idintent_activity = 2131099656;
  TJR_idintent_data = 2131099657;
  TJR_idintent_data_id = 2131099658;
  TJR_idintent_extra_data = 2131099659;
  TJR_idlarge_icon_uri = 2131099660;
  TJR_idmatch_global_nicknames = 2131099653;
  TJR_idnone = 2131099664;
  TJR_idnormal = 2131099665;
  TJR_idplain = 2131099649;
  TJR_idrfc822 = 2131099650;
  TJR_idsatellite = 2131099666;
  TJR_idterrain = 2131099667;
  TJR_idtext1 = 2131099661;
  TJR_idtext2 = 2131099662;

implementation

end.
