//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.b;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  Jb = interface;

  JbClass = interface(JObjectClass)
    ['{DC2895C7-A769-4699-8B24-59BE3783200C}']
    function init(JContextparam0 : JContext) : Jb; cdecl;                       // (Landroid/content/Context;)V A: $1
    procedure a(JStringparam0 : JString; Int64param1 : Int64) ; cdecl;          // (Ljava/lang/String;J)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/b')]
  Jb = interface(JObject)
    ['{3312455E-DDDC-4733-91D5-EDCB058FE537}']
    procedure a(JStringparam0 : JString; Int64param1 : Int64) ; cdecl;          // (Ljava/lang/String;J)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJb = class(TJavaGenericImport<JbClass, Jb>)
  end;

implementation

end.
