//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.c;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.b,
  Androidapi.JNI.GraphicsContentViewText,
  Androidapi.JNI.os,
  android.content.SharedPreferences;

type
  Jc = interface;

  JcClass = interface(JObjectClass)
    ['{913BE9F9-E994-4345-A574-090164DF7F2D}']
    function a(JContextparam0 : JContext) : Jc; cdecl; overload;                // (Landroid/content/Context;)Lcom/google/ads/conversiontracking/c; A: $9
    function d(JStringparam0 : JString) : boolean; cdecl; overload;             // (Ljava/lang/String;)Z A: $1
    procedure a(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure b(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure c(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/c')]
  Jc = interface(JObject)
    ['{16B4EBA0-B51A-4F3C-B111-CDC3E29AC542}']
    function d(JStringparam0 : JString) : boolean; cdecl; overload;             // (Ljava/lang/String;)Z A: $1
    procedure a(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure b(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure c(JStringparam0 : JString) ; cdecl; overload;                     // (Ljava/lang/String;)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJc = class(TJavaGenericImport<JcClass, Jc>)
  end;

implementation

end.
