//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.g;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.e,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.g_c,
  com.google.ads.conversiontracking.i_a,
  android.net.Uri_Builder,
  com.google.ads.conversiontracking.g_b,
  android.net.Uri,
  com.google.ads.conversiontracking.g_a,
  android.content.SharedPreferences;

type
  Jg = interface;

  JgClass = interface(JObjectClass)
    ['{42FEAE02-CD22-41BE-BC70-B08FF2ABED27}']
    function a(JContextparam0 : JContext) : Je; cdecl; overload;                // (Landroid/content/Context;)Lcom/google/ads/conversiontracking/e; A: $9
    function a(JContextparam0 : JContext; JStringparam1 : JString) : Jg_a; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$a; A: $9
    function a(JContextparam0 : JContext; JStringparam1 : JString; JStringparam2 : JString; booleanparam3 : boolean) : boolean; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Z)Z A: $9
    function a(JContextparam0 : JContext; Jg_bparam1 : Jg_b) : boolean; cdecl; overload;// (Landroid/content/Context;Lcom/google/ads/conversiontracking/g$b;)Z A: $9
    function a(JContextparam0 : JContext; Jg_cparam1 : Jg_c) : JString; cdecl; overload;// (Landroid/content/Context;Lcom/google/ads/conversiontracking/g$c;)Ljava/lang/String; A: $9
    function a(JContextparam0 : JContext; Jg_cparam1 : Jg_c; Ji_aparam2 : Ji_a) : JString; cdecl; overload;// (Landroid/content/Context;Lcom/google/ads/conversiontracking/g$c;Lcom/google/ads/conversiontracking/i$a;)Ljava/lang/String; A: $9
    function a(JContextparam0 : JContext; Jg_cparam1 : Jg_c; booleanparam2 : boolean) : boolean; cdecl; overload;// (Landroid/content/Context;Lcom/google/ads/conversiontracking/g$c;Z)Z A: $9
    function a(JObjectparam0 : JObject) : JObject; cdecl; overload;             // (Ljava/lang/Object;)Ljava/lang/Object; A: $9
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $9
    function a(JUriparam0 : JUri) : Jg_b; cdecl; overload;                      // (Landroid/net/Uri;)Lcom/google/ads/conversiontracking/g$b; A: $9
    function a(Jg_aparam0 : Jg_a) : JString; cdecl; overload;                   // (Lcom/google/ads/conversiontracking/g$a;)Ljava/lang/String; A: $9
    function a(Jg_cparam0 : Jg_c) : JString; cdecl; overload;                   // (Lcom/google/ads/conversiontracking/g$c;)Ljava/lang/String; A: $9
    function a(Jg_cparam0 : Jg_c; JStringparam1 : JString; JStringparam2 : JString; Ji_aparam3 : Ji_a; JStringparam4 : JString) : JString; cdecl; overload;// (Lcom/google/ads/conversiontracking/g$c;Ljava/lang/String;Ljava/lang/String;Lcom/google/ads/conversiontracking/i$a;Ljava/lang/String;)Ljava/lang/String; A: $9
    function a(Jg_cparam0 : Jg_c; Ji_aparam1 : Ji_a) : JString; cdecl; overload;// (Lcom/google/ads/conversiontracking/g$c;Lcom/google/ads/conversiontracking/i$a;)Ljava/lang/String; A: $9
    function b(JContextparam0 : JContext) : Int64; cdecl; overload;             // (Landroid/content/Context;)J A: $9
    function b(Jg_cparam0 : Jg_c) : JString; cdecl; overload;                   // (Lcom/google/ads/conversiontracking/g$c;)Ljava/lang/String; A: $9
    function b(Jg_cparam0 : Jg_c; JStringparam1 : JString; JStringparam2 : JString; Ji_aparam3 : Ji_a; JStringparam4 : JString) : JString; cdecl; overload;// (Lcom/google/ads/conversiontracking/g$c;Ljava/lang/String;Ljava/lang/String;Lcom/google/ads/conversiontracking/i$a;Ljava/lang/String;)Ljava/lang/String; A: $9
    function c(Jg_cparam0 : Jg_c; JStringparam1 : JString; JStringparam2 : JString; Ji_aparam3 : Ji_a; JStringparam4 : JString) : JString; cdecl; overload;// (Lcom/google/ads/conversiontracking/g$c;Ljava/lang/String;Ljava/lang/String;Lcom/google/ads/conversiontracking/i$a;Ljava/lang/String;)Ljava/lang/String; A: $9
    function d(JContextparam0 : JContext) : boolean; cdecl;                     // (Landroid/content/Context;)Z A: $9
    procedure a(JContextparam0 : JContext; JStringparam1 : JString; JStringparam2 : JString) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)V A: $9
    procedure c(JContextparam0 : JContext) ; cdecl; overload;                   // (Landroid/content/Context;)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/g$c')]
  Jg = interface(JObject)
    ['{CFC18B1F-B738-48C2-AC7F-7C0661EA0B75}']
  end;

  TJg = class(TJavaGenericImport<JgClass, Jg>)
  end;

implementation

end.
