//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.IAPConversionReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.g_d;

type
  JIAPConversionReporter = interface;

  JIAPConversionReporterClass = interface(JObjectClass)
    ['{500F1146-471C-4F87-90A2-5D23C3C1DDB5}']
    function init(applicationContext : JContext; productId : JString; value : JString; isRepeatable : boolean) : JIAPConversionReporter; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportWithProductId(applicationContext : JContext; productId : JString; value : JString; isRepeatable : boolean) ; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/IAPConversionReporter')]
  JIAPConversionReporter = interface(JObject)
    ['{8A1BBE7F-99A1-4C60-8F3F-E596A8F3BC6D}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJIAPConversionReporter = class(TJavaGenericImport<JIAPConversionReporterClass, JIAPConversionReporter>)
  end;

implementation

end.
