//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.q;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jq = interface;

  JqClass = interface(JObjectClass)
    ['{0CA89BCE-A91B-4E12-A349-3403776CD354}']
    function a : JString; cdecl; overload;                                      // ()Ljava/lang/String; A: $401
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function a(booleanparam0 : boolean) : boolean; cdecl; overload;             // (Z)Z A: $401
    procedure a(JStringparam0 : JString; booleanparam1 : boolean) ; cdecl; overload;// (Ljava/lang/String;Z)V A: $401
  end;

  [JavaSignature('com/google/ads/conversiontracking/q$a')]
  Jq = interface(JObject)
    ['{A776D743-AA2D-4D0A-B102-F8D4ED6EE42E}']
    function a : JString; cdecl; overload;                                      // ()Ljava/lang/String; A: $401
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function a(booleanparam0 : boolean) : boolean; cdecl; overload;             // (Z)Z A: $401
    procedure a(JStringparam0 : JString; booleanparam1 : boolean) ; cdecl; overload;// (Ljava/lang/String;Z)V A: $401
  end;

  TJq = class(TJavaGenericImport<JqClass, Jq>)
  end;

implementation

end.
