//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.DoubleClickConversionReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  JDoubleClickConversionReporter = interface;

  JDoubleClickConversionReporterClass = interface(JObjectClass)
    ['{FE08A949-C4CF-4041-B9FE-986CE8A21C3A}']
    function init(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) : JDoubleClickConversionReporter; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) ; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/DoubleClickConversionReporter')]
  JDoubleClickConversionReporter = interface(JObject)
    ['{4F5EEC3D-B50F-4FE5-AFC4-CE6ED830D99C}']
  end;

  TJDoubleClickConversionReporter = class(TJavaGenericImport<JDoubleClickConversionReporterClass, JDoubleClickConversionReporter>)
  end;

implementation

end.
