//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.n;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.concurrent.BlockingQueue,
  android.content.ComponentName,
  Androidapi.JNI.os;

type
  Jn = interface;

  JnClass = interface(JObjectClass)
    ['{B5D393B5-0959-4E93-8483-01AC4057F759}']
    function a : JIBinder; cdecl;                                               // ()Landroid/os/IBinder; A: $1
    function init : Jn; cdecl;                                                  // ()V A: $1
    procedure onServiceConnected(&name : JComponentName; service : JIBinder) ; cdecl;// (Landroid/content/ComponentName;Landroid/os/IBinder;)V A: $1
    procedure onServiceDisconnected(&name : JComponentName) ; cdecl;            // (Landroid/content/ComponentName;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/n')]
  Jn = interface(JObject)
    ['{2A061533-DB0C-4838-8C9F-A5F2095CBA6A}']
    function a : JIBinder; cdecl;                                               // ()Landroid/os/IBinder; A: $1
    procedure onServiceConnected(&name : JComponentName; service : JIBinder) ; cdecl;// (Landroid/content/ComponentName;Landroid/os/IBinder;)V A: $1
    procedure onServiceDisconnected(&name : JComponentName) ; cdecl;            // (Landroid/content/ComponentName;)V A: $1
  end;

  TJn = class(TJavaGenericImport<JnClass, Jn>)
  end;

implementation

end.
