//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.g_2;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jg_2 = interface;

  Jg_2Class = interface(JObjectClass)
    ['{4BACB5F8-8734-486B-859E-245DF43B848E}']
  end;

  [JavaSignature('com/google/ads/conversiontracking/g_2')]
  Jg_2 = interface(JObject)
    ['{452B9723-63DF-4C2F-BC55-80DB6EDD5BB5}']
  end;

  TJg_2 = class(TJavaGenericImport<Jg_2Class, Jg_2>)
  end;

implementation

end.
