//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.e_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.e,
  com.google.ads.conversiontracking.d;

type
  Je_1 = interface;

  Je_1Class = interface(JObjectClass)
    ['{2A6F5AA7-E87A-4FCD-83B3-725082F3C786}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/e_1')]
  Je_1 = interface(JObject)
    ['{D8B7FD42-DED3-4F27-9C40-9E35D4D71F1E}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJe_1 = class(TJavaGenericImport<Je_1Class, Je_1>)
  end;

implementation

end.
