//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.GoogleConversionPing_ConversionType;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JGoogleConversionPing_ConversionType = interface;

  JGoogleConversionPing_ConversionTypeClass = interface(JObjectClass)
    ['{C1928CF3-1464-4692-8A58-9E57BAD9C95C}']
    function _GetDOUBLECLICK_CONVERSION : JGoogleConversionPing_ConversionType; cdecl;//  A: $4019
    function _GetGOOGLE_CONVERSION : JGoogleConversionPing_ConversionType; cdecl;//  A: $4019
    function valueOf(&name : JString) : JGoogleConversionPing_ConversionType; cdecl;// (Ljava/lang/String;)Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $9
    function values : TJavaArray<JGoogleConversionPing_ConversionType>; cdecl;  // ()[Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $9
    property DOUBLECLICK_CONVERSION : JGoogleConversionPing_ConversionType read _GetDOUBLECLICK_CONVERSION;// Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $4019
    property GOOGLE_CONVERSION : JGoogleConversionPing_ConversionType read _GetGOOGLE_CONVERSION;// Lcom/google/ads/conversiontracking/GoogleConversionPing$ConversionType; A: $4019
  end;

  [JavaSignature('com/google/ads/conversiontracking/GoogleConversionPing_ConversionType')]
  JGoogleConversionPing_ConversionType = interface(JObject)
    ['{8F065CE6-2A9F-4570-853F-04BD62AD9B52}']
  end;

  TJGoogleConversionPing_ConversionType = class(TJavaGenericImport<JGoogleConversionPing_ConversionTypeClass, JGoogleConversionPing_ConversionType>)
  end;

implementation

end.
