//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.DoubleClickAudienceReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  JDoubleClickAudienceReporter = interface;

  JDoubleClickAudienceReporterClass = interface(JObjectClass)
    ['{3B1DE7B8-B9E9-4CC4-ACC4-8F8E2C7D97DE}']
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportActivity(applicationContext : JContext; adUnitId : JString; customParameters : JMap) ; cdecl;// (Landroid/content/Context;Ljava/lang/String;Ljava/util/Map;)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/DoubleClickAudienceReporter')]
  JDoubleClickAudienceReporter = interface(JObject)
    ['{EB4C3B88-6992-4478-A363-A0CF8AB77B2A}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJDoubleClickAudienceReporter = class(TJavaGenericImport<JDoubleClickAudienceReporterClass, JDoubleClickAudienceReporter>)
  end;

implementation

end.
