//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.e;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.f,
  com.google.ads.conversiontracking.g_c,
  com.google.ads.conversiontracking.d;

type
  Je = interface;

  JeClass = interface(JObjectClass)
    ['{55B7B371-100B-445E-BA23-731B8A40EAAB}']
    function init(JContextparam0 : JContext) : Je; cdecl;                       // (Landroid/content/Context;)V A: $1
    procedure a(JStringparam0 : JString; Jg_cparam1 : Jg_c; booleanparam2 : boolean; booleanparam3 : boolean; booleanparam4 : boolean) ; cdecl; overload;// (Ljava/lang/String;Lcom/google/ads/conversiontracking/g$c;ZZZ)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/e$b')]
  Je = interface(JObject)
    ['{325A9D5B-EFDA-4A48-9699-3CAD885A89BA}']
    procedure a(JStringparam0 : JString; Jg_cparam1 : Jg_c; booleanparam2 : boolean; booleanparam3 : boolean; booleanparam4 : boolean) ; cdecl; overload;// (Ljava/lang/String;Lcom/google/ads/conversiontracking/g$c;ZZZ)V A: $1
  end;

  TJe = class(TJavaGenericImport<JeClass, Je>)
  end;

implementation

end.
