//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.m;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.content.Intent;

type
  Jm = interface;

  JmClass = interface(JObjectClass)
    ['{34C40B32-B8AD-4A76-9D0D-BCA5F42331AA}']
    function init(JStringparam0 : JString; JIntentparam1 : JIntent) : Jm; cdecl;// (Ljava/lang/String;Landroid/content/Intent;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/m')]
  Jm = interface(JObject)
    ['{19856055-CCC3-4798-853D-03D642CDE5C7}']
  end;

  TJm = class(TJavaGenericImport<JmClass, Jm>)
  end;

implementation

end.
