//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.q_a_a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.os;

type
  Jq_a_a = interface;

  Jq_a_aClass = interface(JObjectClass)
    ['{451D8651-A14C-464B-8939-6205CBDA6F62}']
    function a : JString; cdecl; overload;                                      // ()Ljava/lang/String; A: $1
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function a(booleanparam0 : boolean) : boolean; cdecl; overload;             // (Z)Z A: $1
    function asBinder : JIBinder; cdecl;                                        // ()Landroid/os/IBinder; A: $1
    procedure a(JStringparam0 : JString; booleanparam1 : boolean) ; cdecl; overload;// (Ljava/lang/String;Z)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/q_a_a')]
  Jq_a_a = interface(JObject)
    ['{92F22E79-F95A-4038-9CBF-4A4F2DC9788B}']
    function a : JString; cdecl; overload;                                      // ()Ljava/lang/String; A: $1
    function a(JStringparam0 : JString) : JString; cdecl; overload;             // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function a(booleanparam0 : boolean) : boolean; cdecl; overload;             // (Z)Z A: $1
    function asBinder : JIBinder; cdecl;                                        // ()Landroid/os/IBinder; A: $1
    procedure a(JStringparam0 : JString; booleanparam1 : boolean) ; cdecl; overload;// (Ljava/lang/String;Z)V A: $1
  end;

  TJq_a_a = class(TJavaGenericImport<Jq_a_aClass, Jq_a_a>)
  end;

implementation

end.
