//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.h;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jh = interface;

  JhClass = interface(JObjectClass)
    ['{4F73ED31-EF36-41C5-859A-0A7ECE482A08}']
  end;

  [JavaSignature('com/google/ads/conversiontracking/h$a')]
  Jh = interface(JObject)
    ['{136718C1-223B-419E-9A97-B3CC8828419F}']
  end;

  TJh = class(TJavaGenericImport<JhClass, Jh>)
  end;

implementation

end.
