//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.q_a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.q,
  Androidapi.JNI.os;

type
  Jq_a = interface;

  Jq_aClass = interface(JObjectClass)
    ['{8BB8000C-B4B5-48D2-8497-C5798794576B}']
    function a(JIBinderparam0 : JIBinder) : Jq; cdecl;                          // (Landroid/os/IBinder;)Lcom/google/ads/conversiontracking/q; A: $9
    function onTransact(code : Integer; data : JParcel; reply : JParcel; flags : Integer) : boolean; cdecl;// (ILandroid/os/Parcel;Landroid/os/Parcel;I)Z A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/q$a$a')]
  Jq_a = interface(JObject)
    ['{25595D67-0338-4187-97FD-CF076A985FD6}']
    function onTransact(code : Integer; data : JParcel; reply : JParcel; flags : Integer) : boolean; cdecl;// (ILandroid/os/Parcel;Landroid/os/Parcel;I)Z A: $1
  end;

  TJq_a = class(TJavaGenericImport<Jq_aClass, Jq_a>)
  end;

implementation

end.
