//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.a_c;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  Ja_c = interface;

  Ja_cClass = interface(JObjectClass)
    ['{3C278BF3-B323-42B9-B329-A10047B4D177}']
    function getString(id : Integer) : JString; cdecl;                          // (I)Ljava/lang/String; A: $1
    function init(JResourcesparam0 : JResources) : Ja_c; cdecl;                 // (Landroid/content/res/Resources;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/a_c')]
  Ja_c = interface(JObject)
    ['{86B161FB-3F1B-491F-A2C1-9C5E6683501D}']
    function getString(id : Integer) : JString; cdecl;                          // (I)Ljava/lang/String; A: $1
  end;

  TJa_c = class(TJavaGenericImport<Ja_cClass, Ja_c>)
  end;

implementation

end.
