//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.f;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.d,
  android.database.sqlite.SQLiteDatabase,
  android.database.Cursor;

type
  Jf_a = interface; // merged
  Jf = interface;

  JfClass = interface(JObjectClass)
    ['{CF46C440-BE7B-4891-B955-FE2D20D0D18F}']
    function a : JSQLiteDatabase; cdecl; overload;                              // ()Landroid/database/sqlite/SQLiteDatabase; A: $1
    function a(Int64param0 : Int64) : JList; cdecl; overload;                   // (J)Ljava/util/List; A: $1
    function a(JCursorparam0 : JCursor) : Jd; cdecl; overload;                  // (Landroid/database/Cursor;)Lcom/google/ads/conversiontracking/d; A: $1
    function c : Integer; cdecl; overload;                                      // ()I A: $1
    function init(JContextparam0 : JContext) : Jf; cdecl;                       // (Landroid/content/Context;)V A: $1
    procedure a(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure b ; cdecl; overload;                                              // ()V A: $1
    procedure b(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure c(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure d ; cdecl;                                                        // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/f$a')]
  Jf = interface(JObject)
    ['{6DAD064F-12DF-406D-AFDB-A665BDDC2251}']
    function a : JSQLiteDatabase; cdecl; overload;                              // ()Landroid/database/sqlite/SQLiteDatabase; A: $1
    function a(Int64param0 : Int64) : JList; cdecl; overload;                   // (J)Ljava/util/List; A: $1
    function a(JCursorparam0 : JCursor) : Jd; cdecl; overload;                  // (Landroid/database/Cursor;)Lcom/google/ads/conversiontracking/d; A: $1
    function c : Integer; cdecl; overload;                                      // ()I A: $1
    procedure a(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure b ; cdecl; overload;                                              // ()V A: $1
    procedure b(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure c(Jdparam0 : Jd) ; cdecl; overload;                               // (Lcom/google/ads/conversiontracking/d;)V A: $1
    procedure d ; cdecl;                                                        // ()V A: $1
  end;

  TJf = class(TJavaGenericImport<JfClass, Jf>)
  end;

  // Merged from: .\com.google.ads.conversiontracking.f_a.pas
  Jf_aClass = interface(JObjectClass)
    ['{ABD02435-D96F-49E0-9A27-5F86D9FFBF56}']
    function init(Jfparam0 : Jf; JContextparam1 : JContext; JStringparam2 : JString) : Jf_a; cdecl;// (Lcom/google/ads/conversiontracking/f;Landroid/content/Context;Ljava/lang/String;)V A: $1
    procedure onCreate(db : JSQLiteDatabase) ; cdecl;                           // (Landroid/database/sqlite/SQLiteDatabase;)V A: $1
    procedure onUpgrade(db : JSQLiteDatabase; oldVersion : Integer; newVersion : Integer) ; cdecl;// (Landroid/database/sqlite/SQLiteDatabase;II)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/f_a')]
  Jf_a = interface(JObject)
    ['{09224C1C-CF70-4983-A4A1-2563A0DAF07B}']
    procedure onCreate(db : JSQLiteDatabase) ; cdecl;                           // (Landroid/database/sqlite/SQLiteDatabase;)V A: $1
    procedure onUpgrade(db : JSQLiteDatabase; oldVersion : Integer; newVersion : Integer) ; cdecl;// (Landroid/database/sqlite/SQLiteDatabase;II)V A: $1
  end;

  TJf_a = class(TJavaGenericImport<Jf_aClass, Jf_a>)
  end;


implementation

end.
