//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.InstallReceiver;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  android.content.Intent;

type
  JInstallReceiver = interface;

  JInstallReceiverClass = interface(JObjectClass)
    ['{BD0C47D1-75E0-42E7-9C0B-3F1A66260AA8}']
    function init : JInstallReceiver; cdecl;                                    // ()V A: $1
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/InstallReceiver')]
  JInstallReceiver = interface(JObject)
    ['{27909C88-AEA5-4855-852E-5A11D3AE10E1}']
    procedure onReceive(context : JContext; intent : JIntent) ; cdecl;          // (Landroid/content/Context;Landroid/content/Intent;)V A: $1
  end;

  TJInstallReceiver = class(TJavaGenericImport<JInstallReceiverClass, JInstallReceiver>)
  end;

implementation

end.
