//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.AdWordsConversionReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.g_d,
  android.net.Uri;

type
  JAdWordsConversionReporter = interface;

  JAdWordsConversionReporterClass = interface(JObjectClass)
    ['{ACE75B20-0F7A-4A58-B9B7-DBCD52CE979D}']
    function init(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; currencyCode : JString; isRepeatable : boolean) : JAdWordsConversionReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    function init(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) : JAdWordsConversionReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    function registerReferrer(applicationContext : JContext; clickUri : JUri) : boolean; cdecl;// (Landroid/content/Context;Landroid/net/Uri;)Z A: $9
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; currencyCode : JString; isRepeatable : boolean) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; &label : JString; value : JString; isRepeatable : boolean) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/AdWordsConversionReporter')]
  JAdWordsConversionReporter = interface(JObject)
    ['{BE71CE56-B4C0-44C9-9A8F-B791285E549B}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJAdWordsConversionReporter = class(TJavaGenericImport<JAdWordsConversionReporterClass, JAdWordsConversionReporter>)
  end;

implementation

end.
