//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_integer;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_integer = interface;

  JR_integerClass = interface(JObjectClass)
    ['{C05A4E84-DC3B-4169-BAAB-C59A4AFAB33C}']
    function _Getgoogle_play_services_version : Integer; cdecl;                 //  A: $19
    function init : JR_integer; cdecl;                                          // ()V A: $1
    property google_play_services_version : Integer read _Getgoogle_play_services_version;// I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_integer')]
  JR_integer = interface(JObject)
    ['{2FB272BD-C3F3-4BC3-B857-2C91DC0E113E}']
  end;

  TJR_integer = class(TJavaGenericImport<JR_integerClass, JR_integer>)
  end;

const
  TJR_integergoogle_play_services_version = 2131034112;

implementation

end.
