//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.e_b;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.e;

type
  Je_b = interface;

  Je_bClass = interface(JObjectClass)
    ['{BF059807-E373-4712-8FF5-FE623909E8A1}']
    function init(Jeparam0 : Je) : Je_b; cdecl;                                 // (Lcom/google/ads/conversiontracking/e;)V A: $1
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/e_b')]
  Je_b = interface(JObject)
    ['{3EF5A2B7-E197-4AB3-B182-F4D022A29CC7}']
    procedure run ; cdecl;                                                      // ()V A: $1
  end;

  TJe_b = class(TJavaGenericImport<Je_bClass, Je_b>)
  end;

implementation

end.
