//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR = interface;

  JRClass = interface(JObjectClass)
    ['{FDBC3185-56EE-4BAC-923A-4381CD1861D2}']
    function init : JR; cdecl;                                                  // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/R$styleable')]
  JR = interface(JObject)
    ['{1466DAE4-1710-4E8D-9EF1-15A133D1A7D6}']
  end;

  TJR = class(TJavaGenericImport<JRClass, JR>)
  end;

implementation

end.
