//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.i;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.n,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.i_a;

type
  Ji = interface;

  JiClass = interface(JObjectClass)
    ['{A15FDB01-9AE4-4323-91F6-BE6F00ED20D7}']
    function a(JContextparam0 : JContext) : Ji_a; cdecl; overload;              // (Landroid/content/Context;)Lcom/google/ads/conversiontracking/i$a; A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/i$a')]
  Ji = interface(JObject)
    ['{4718D5FC-ED68-4887-BD35-98BDF185DBA6}']
  end;

  TJi = class(TJavaGenericImport<JiClass, Ji>)
  end;

implementation

end.
