//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.k;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  android.content.Intent;

type
  Jk = interface;

  JkClass = interface(JObjectClass)
    ['{E6CBB6B7-6B77-4734-831D-C7C5891E54F8}']
  end;

  [JavaSignature('com/google/ads/conversiontracking/k')]
  Jk = interface(JObject)
    ['{9A7BD1CF-4F00-4F6A-A803-9C95A37EA8C4}']
  end;

  TJk = class(TJavaGenericImport<JkClass, Jk>)
  end;

implementation

end.
