//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.h_a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Jh_a = interface;

  Jh_aClass = interface(JObjectClass)
    ['{979B17E3-E9AF-417A-B496-6CB4B64F2D4E}']
    function _Geta : Integer; cdecl;                                            //  A: $19
    property a : Integer read _Geta;                                            // I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/h_a')]
  Jh_a = interface(JObject)
    ['{7520D13C-C449-47E0-910F-D941FB1F952F}']
  end;

  TJh_a = class(TJavaGenericImport<Jh_aClass, Jh_a>)
  end;

const
  TJh_aa = 2130968589;

implementation

end.
