//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.R_styleable;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JR_styleable = interface;

  JR_styleableClass = interface(JObjectClass)
    ['{5ADF0D9C-AC86-4133-A3CA-A9DF8A64215E}']
    function _GetAdsAttrs : TJavaArray<Integer>; cdecl;                         //  A: $19
    function _GetAdsAttrs_adSize : Integer; cdecl;                              //  A: $19
    function _GetAdsAttrs_adSizes : Integer; cdecl;                             //  A: $19
    function _GetAdsAttrs_adUnitId : Integer; cdecl;                            //  A: $19
    function _GetAppDataSearch : TJavaArray<Integer>; cdecl;                    //  A: $19
    function _GetCorpus : TJavaArray<Integer>; cdecl;                           //  A: $19
    function _GetCorpus_contentProviderUri : Integer; cdecl;                    //  A: $19
    function _GetCorpus_corpusId : Integer; cdecl;                              //  A: $19
    function _GetCorpus_corpusVersion : Integer; cdecl;                         //  A: $19
    function _GetCorpus_trimmable : Integer; cdecl;                             //  A: $19
    function _GetFeatureParam : TJavaArray<Integer>; cdecl;                     //  A: $19
    function _GetFeatureParam_paramName : Integer; cdecl;                       //  A: $19
    function _GetFeatureParam_paramValue : Integer; cdecl;                      //  A: $19
    function _GetGlobalSearch : TJavaArray<Integer>; cdecl;                     //  A: $19
    function _GetGlobalSearchCorpus : TJavaArray<Integer>; cdecl;               //  A: $19
    function _GetGlobalSearchCorpus_allowShortcuts : Integer; cdecl;            //  A: $19
    function _GetGlobalSearchSection : TJavaArray<Integer>; cdecl;              //  A: $19
    function _GetGlobalSearchSection_sectionContent : Integer; cdecl;           //  A: $19
    function _GetGlobalSearchSection_sectionType : Integer; cdecl;              //  A: $19
    function _GetGlobalSearch_defaultIntentAction : Integer; cdecl;             //  A: $19
    function _GetGlobalSearch_defaultIntentActivity : Integer; cdecl;           //  A: $19
    function _GetGlobalSearch_defaultIntentData : Integer; cdecl;               //  A: $19
    function _GetGlobalSearch_searchEnabled : Integer; cdecl;                   //  A: $19
    function _GetGlobalSearch_searchLabel : Integer; cdecl;                     //  A: $19
    function _GetGlobalSearch_settingsDescription : Integer; cdecl;             //  A: $19
    function _GetMapAttrs : TJavaArray<Integer>; cdecl;                         //  A: $19
    function _GetMapAttrs_cameraBearing : Integer; cdecl;                       //  A: $19
    function _GetMapAttrs_cameraTargetLat : Integer; cdecl;                     //  A: $19
    function _GetMapAttrs_cameraTargetLng : Integer; cdecl;                     //  A: $19
    function _GetMapAttrs_cameraTilt : Integer; cdecl;                          //  A: $19
    function _GetMapAttrs_cameraZoom : Integer; cdecl;                          //  A: $19
    function _GetMapAttrs_mapType : Integer; cdecl;                             //  A: $19
    function _GetMapAttrs_uiCompass : Integer; cdecl;                           //  A: $19
    function _GetMapAttrs_uiRotateGestures : Integer; cdecl;                    //  A: $19
    function _GetMapAttrs_uiScrollGestures : Integer; cdecl;                    //  A: $19
    function _GetMapAttrs_uiTiltGestures : Integer; cdecl;                      //  A: $19
    function _GetMapAttrs_uiZoomControls : Integer; cdecl;                      //  A: $19
    function _GetMapAttrs_uiZoomGestures : Integer; cdecl;                      //  A: $19
    function _GetMapAttrs_useViewLifecycle : Integer; cdecl;                    //  A: $19
    function _GetMapAttrs_zOrderOnTop : Integer; cdecl;                         //  A: $19
    function _GetSection : TJavaArray<Integer>; cdecl;                          //  A: $19
    function _GetSectionFeature : TJavaArray<Integer>; cdecl;                   //  A: $19
    function _GetSectionFeature_featureType : Integer; cdecl;                   //  A: $19
    function _GetSection_indexPrefixes : Integer; cdecl;                        //  A: $19
    function _GetSection_noIndex : Integer; cdecl;                              //  A: $19
    function _GetSection_sectionFormat : Integer; cdecl;                        //  A: $19
    function _GetSection_sectionId : Integer; cdecl;                            //  A: $19
    function _GetSection_sectionWeight : Integer; cdecl;                        //  A: $19
    function _GetSection_subsectionSeparator : Integer; cdecl;                  //  A: $19
    function init : JR_styleable; cdecl;                                        // ()V A: $1
    property AdsAttrs : TJavaArray<Integer> read _GetAdsAttrs;                  // [I A: $19
    property AdsAttrs_adSize : Integer read _GetAdsAttrs_adSize;                // I A: $19
    property AdsAttrs_adSizes : Integer read _GetAdsAttrs_adSizes;              // I A: $19
    property AdsAttrs_adUnitId : Integer read _GetAdsAttrs_adUnitId;            // I A: $19
    property AppDataSearch : TJavaArray<Integer> read _GetAppDataSearch;        // [I A: $19
    property Corpus : TJavaArray<Integer> read _GetCorpus;                      // [I A: $19
    property Corpus_contentProviderUri : Integer read _GetCorpus_contentProviderUri;// I A: $19
    property Corpus_corpusId : Integer read _GetCorpus_corpusId;                // I A: $19
    property Corpus_corpusVersion : Integer read _GetCorpus_corpusVersion;      // I A: $19
    property Corpus_trimmable : Integer read _GetCorpus_trimmable;              // I A: $19
    property FeatureParam : TJavaArray<Integer> read _GetFeatureParam;          // [I A: $19
    property FeatureParam_paramName : Integer read _GetFeatureParam_paramName;  // I A: $19
    property FeatureParam_paramValue : Integer read _GetFeatureParam_paramValue;// I A: $19
    property GlobalSearch : TJavaArray<Integer> read _GetGlobalSearch;          // [I A: $19
    property GlobalSearchCorpus : TJavaArray<Integer> read _GetGlobalSearchCorpus;// [I A: $19
    property GlobalSearchCorpus_allowShortcuts : Integer read _GetGlobalSearchCorpus_allowShortcuts;// I A: $19
    property GlobalSearchSection : TJavaArray<Integer> read _GetGlobalSearchSection;// [I A: $19
    property GlobalSearchSection_sectionContent : Integer read _GetGlobalSearchSection_sectionContent;// I A: $19
    property GlobalSearchSection_sectionType : Integer read _GetGlobalSearchSection_sectionType;// I A: $19
    property GlobalSearch_defaultIntentAction : Integer read _GetGlobalSearch_defaultIntentAction;// I A: $19
    property GlobalSearch_defaultIntentActivity : Integer read _GetGlobalSearch_defaultIntentActivity;// I A: $19
    property GlobalSearch_defaultIntentData : Integer read _GetGlobalSearch_defaultIntentData;// I A: $19
    property GlobalSearch_searchEnabled : Integer read _GetGlobalSearch_searchEnabled;// I A: $19
    property GlobalSearch_searchLabel : Integer read _GetGlobalSearch_searchLabel;// I A: $19
    property GlobalSearch_settingsDescription : Integer read _GetGlobalSearch_settingsDescription;// I A: $19
    property MapAttrs : TJavaArray<Integer> read _GetMapAttrs;                  // [I A: $19
    property MapAttrs_cameraBearing : Integer read _GetMapAttrs_cameraBearing;  // I A: $19
    property MapAttrs_cameraTargetLat : Integer read _GetMapAttrs_cameraTargetLat;// I A: $19
    property MapAttrs_cameraTargetLng : Integer read _GetMapAttrs_cameraTargetLng;// I A: $19
    property MapAttrs_cameraTilt : Integer read _GetMapAttrs_cameraTilt;        // I A: $19
    property MapAttrs_cameraZoom : Integer read _GetMapAttrs_cameraZoom;        // I A: $19
    property MapAttrs_mapType : Integer read _GetMapAttrs_mapType;              // I A: $19
    property MapAttrs_uiCompass : Integer read _GetMapAttrs_uiCompass;          // I A: $19
    property MapAttrs_uiRotateGestures : Integer read _GetMapAttrs_uiRotateGestures;// I A: $19
    property MapAttrs_uiScrollGestures : Integer read _GetMapAttrs_uiScrollGestures;// I A: $19
    property MapAttrs_uiTiltGestures : Integer read _GetMapAttrs_uiTiltGestures;// I A: $19
    property MapAttrs_uiZoomControls : Integer read _GetMapAttrs_uiZoomControls;// I A: $19
    property MapAttrs_uiZoomGestures : Integer read _GetMapAttrs_uiZoomGestures;// I A: $19
    property MapAttrs_useViewLifecycle : Integer read _GetMapAttrs_useViewLifecycle;// I A: $19
    property MapAttrs_zOrderOnTop : Integer read _GetMapAttrs_zOrderOnTop;      // I A: $19
    property Section : TJavaArray<Integer> read _GetSection;                    // [I A: $19
    property SectionFeature : TJavaArray<Integer> read _GetSectionFeature;      // [I A: $19
    property SectionFeature_featureType : Integer read _GetSectionFeature_featureType;// I A: $19
    property Section_indexPrefixes : Integer read _GetSection_indexPrefixes;    // I A: $19
    property Section_noIndex : Integer read _GetSection_noIndex;                // I A: $19
    property Section_sectionFormat : Integer read _GetSection_sectionFormat;    // I A: $19
    property Section_sectionId : Integer read _GetSection_sectionId;            // I A: $19
    property Section_sectionWeight : Integer read _GetSection_sectionWeight;    // I A: $19
    property Section_subsectionSeparator : Integer read _GetSection_subsectionSeparator;// I A: $19
  end;

  [JavaSignature('com/google/ads/conversiontracking/R_styleable')]
  JR_styleable = interface(JObject)
    ['{31812A45-5F78-4927-AAB7-574B70C72F8A}']
  end;

  TJR_styleable = class(TJavaGenericImport<JR_styleableClass, JR_styleable>)
  end;

const
  TJR_styleableAdsAttrs_adSize = 0;
  TJR_styleableAdsAttrs_adSizes = 1;
  TJR_styleableAdsAttrs_adUnitId = 2;
  TJR_styleableCorpus_contentProviderUri = 2;
  TJR_styleableCorpus_corpusId = 0;
  TJR_styleableCorpus_corpusVersion = 1;
  TJR_styleableCorpus_trimmable = 3;
  TJR_styleableFeatureParam_paramName = 0;
  TJR_styleableFeatureParam_paramValue = 1;
  TJR_styleableGlobalSearch_defaultIntentAction = 3;
  TJR_styleableGlobalSearch_defaultIntentActivity = 5;
  TJR_styleableGlobalSearch_defaultIntentData = 4;
  TJR_styleableGlobalSearch_searchEnabled = 0;
  TJR_styleableGlobalSearch_searchLabel = 1;
  TJR_styleableGlobalSearch_settingsDescription = 2;
  TJR_styleableGlobalSearchCorpus_allowShortcuts = 0;
  TJR_styleableGlobalSearchSection_sectionContent = 1;
  TJR_styleableGlobalSearchSection_sectionType = 0;
  TJR_styleableMapAttrs_cameraBearing = 1;
  TJR_styleableMapAttrs_cameraTargetLat = 2;
  TJR_styleableMapAttrs_cameraTargetLng = 3;
  TJR_styleableMapAttrs_cameraTilt = 4;
  TJR_styleableMapAttrs_cameraZoom = 5;
  TJR_styleableMapAttrs_mapType = 0;
  TJR_styleableMapAttrs_uiCompass = 6;
  TJR_styleableMapAttrs_uiRotateGestures = 7;
  TJR_styleableMapAttrs_uiScrollGestures = 8;
  TJR_styleableMapAttrs_uiTiltGestures = 9;
  TJR_styleableMapAttrs_uiZoomControls = 10;
  TJR_styleableMapAttrs_uiZoomGestures = 11;
  TJR_styleableMapAttrs_useViewLifecycle = 12;
  TJR_styleableMapAttrs_zOrderOnTop = 13;
  TJR_styleableSection_indexPrefixes = 4;
  TJR_styleableSection_noIndex = 2;
  TJR_styleableSection_sectionFormat = 1;
  TJR_styleableSection_sectionId = 0;
  TJR_styleableSection_sectionWeight = 3;
  TJR_styleableSection_subsectionSeparator = 5;
  TJR_styleableSectionFeature_featureType = 0;

implementation

end.
