//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.g_c;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.g_d,
  com.google.ads.conversiontracking.g_a;

type
  Jg_c = interface;

  Jg_cClass = interface(JObjectClass)
    ['{2863B025-7F87-44F3-8519-5DAEBFAFB775}']
    function a : Jg_c; cdecl; overload;                                         // ()Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(Int64param0 : Int64) : Jg_c; cdecl; overload;                    // (J)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(JMapparam0 : JMap) : Jg_c; cdecl; overload;                      // (Ljava/util/Map;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(JStringparam0 : JString) : Jg_c; cdecl; overload;                // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(Jg_aparam0 : Jg_a) : Jg_c; cdecl; overload;                      // (Lcom/google/ads/conversiontracking/g$a;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(Jg_dparam0 : Jg_d) : Jg_c; cdecl; overload;                      // (Lcom/google/ads/conversiontracking/g$d;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(booleanparam0 : boolean) : Jg_c; cdecl; overload;                // (Z)Lcom/google/ads/conversiontracking/g$c; A: $1
    function b : Jg_c; cdecl; overload;                                         // ()Lcom/google/ads/conversiontracking/g$c; A: $1
    function b(JStringparam0 : JString) : Jg_c; cdecl; overload;                // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function c(JStringparam0 : JString) : Jg_c; cdecl;                          // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function d(JStringparam0 : JString) : Jg_c; cdecl;                          // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function e(JStringparam0 : JString) : Jg_c; cdecl;                          // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function init : Jg_c; cdecl;                                                // ()V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/g_c')]
  Jg_c = interface(JObject)
    ['{707683A4-0592-48AB-B828-AF952B5D1A9A}']
    function a : Jg_c; cdecl; overload;                                         // ()Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(Int64param0 : Int64) : Jg_c; cdecl; overload;                    // (J)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(JMapparam0 : JMap) : Jg_c; cdecl; overload;                      // (Ljava/util/Map;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(JStringparam0 : JString) : Jg_c; cdecl; overload;                // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(Jg_aparam0 : Jg_a) : Jg_c; cdecl; overload;                      // (Lcom/google/ads/conversiontracking/g$a;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(Jg_dparam0 : Jg_d) : Jg_c; cdecl; overload;                      // (Lcom/google/ads/conversiontracking/g$d;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function a(booleanparam0 : boolean) : Jg_c; cdecl; overload;                // (Z)Lcom/google/ads/conversiontracking/g$c; A: $1
    function b : Jg_c; cdecl; overload;                                         // ()Lcom/google/ads/conversiontracking/g$c; A: $1
    function b(JStringparam0 : JString) : Jg_c; cdecl; overload;                // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function c(JStringparam0 : JString) : Jg_c; cdecl;                          // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function d(JStringparam0 : JString) : Jg_c; cdecl;                          // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
    function e(JStringparam0 : JString) : Jg_c; cdecl;                          // (Ljava/lang/String;)Lcom/google/ads/conversiontracking/g$c; A: $1
  end;

  TJg_c = class(TJavaGenericImport<Jg_cClass, Jg_c>)
  end;

implementation

end.
