//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.AdWordsRemarketingReporter;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText;

type
  JAdWordsRemarketingReporter = interface;

  JAdWordsRemarketingReporterClass = interface(JObjectClass)
    ['{B099689E-67AD-45BD-A8AB-1F1C27873BE9}']
    function init(applicationContext : JContext; conversionId : JString) : JAdWordsRemarketingReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;)V A: $1
    function init(applicationContext : JContext; conversionId : JString; customParameters : JMap) : JAdWordsRemarketingReporter; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/util/Map;)V A: $1
    procedure report ; cdecl;                                                   // ()V A: $1
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;)V A: $9
    procedure reportWithConversionId(applicationContext : JContext; conversionId : JString; customParameters : JMap) ; cdecl; overload;// (Landroid/content/Context;Ljava/lang/String;Ljava/util/Map;)V A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/AdWordsRemarketingReporter')]
  JAdWordsRemarketingReporter = interface(JObject)
    ['{D2961E58-C41D-4B63-A03D-523016A83565}']
    procedure report ; cdecl;                                                   // ()V A: $1
  end;

  TJAdWordsRemarketingReporter = class(TJavaGenericImport<JAdWordsRemarketingReporterClass, JAdWordsRemarketingReporter>)
  end;

implementation

end.
