//
// Generated by JavaToPas v1.5 20161018 - 181707
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.s;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  Js = interface;

  JsClass = interface(JObjectClass)
    ['{63364E01-F1D0-4D96-8782-5B4AE7E197DA}']
    function a(TJavaArrayByteparam0 : TJavaArray<Byte>; Integerparam1 : Integer; Integerparam2 : Integer; TJavaArrayCharparam3 : TJavaArray<Char>; booleanparam4 : boolean) : JString; cdecl; overload;// ([BII[CZ)Ljava/lang/String; A: $9
    function a(TJavaArrayByteparam0 : TJavaArray<Byte>; booleanparam1 : boolean) : JString; deprecated; cdecl; overload;// ([BZ)Ljava/lang/String; A: $9
  end;

  [JavaSignature('com/google/ads/conversiontracking/s')]
  Js = interface(JObject)
    ['{269CB97D-2AA4-4DC8-84C0-528D10D6AE30}']
  end;

  TJs = class(TJavaGenericImport<JsClass, Js>)
  end;

implementation

end.
