//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.a_a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  com.google.ads.conversiontracking.a_b,
  com.google.ads.conversiontracking.a_c,
  Androidapi.JNI.GraphicsContentViewText;

type
  Ja_a = interface;

  Ja_aClass = interface(JObjectClass)
    ['{0F394F2F-4F45-4031-82FF-1D8FF0B5C3AE}']
    function getPackageManager : JPackageManager; cdecl;                        // ()Landroid/content/pm/PackageManager; A: $1
    function getResources : JResources; cdecl;                                  // ()Landroid/content/res/Resources; A: $1
    function init(JContextparam0 : JContext) : Ja_a; cdecl;                     // (Landroid/content/Context;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/a_a')]
  Ja_a = interface(JObject)
    ['{2AE5E504-2B6A-49FD-8506-5BD4DDE60E98}']
    function getPackageManager : JPackageManager; cdecl;                        // ()Landroid/content/pm/PackageManager; A: $1
    function getResources : JResources; cdecl;                                  // ()Landroid/content/res/Resources; A: $1
  end;

  TJa_a = class(TJavaGenericImport<Ja_aClass, Ja_a>)
  end;

implementation

end.
