//
// Generated by JavaToPas v1.5 20161018 - 181706
////////////////////////////////////////////////////////////////////////////////
unit com.google.ads.conversiontracking.a;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  Androidapi.JNI.GraphicsContentViewText,
  com.google.ads.conversiontracking.i_a;

type
  Ja = interface;

  JaClass = interface(JObjectClass)
    ['{94773B5C-E24A-4000-9BAC-3A9AABEE2D7C}']
    function a : Ji_a; cdecl;                                                   // ()Lcom/google/ads/conversiontracking/i$a; A: $1
    function init(JContextparam0 : JContext) : Ja; cdecl;                       // (Landroid/content/Context;)V A: $1
  end;

  [JavaSignature('com/google/ads/conversiontracking/a$b')]
  Ja = interface(JObject)
    ['{8E530582-014F-4FE7-92E3-E999AF279935}']
    function a : Ji_a; cdecl;                                                   // ()Lcom/google/ads/conversiontracking/i$a; A: $1
  end;

  TJa = class(TJavaGenericImport<JaClass, Ja>)
  end;

implementation

end.
